Repository ucsd-cse125-sp23/group-4, pull requests merged in 2023-05, with the labels that each got.

#22 Add basic networking components
  CMakeLists.txt
  include/client/graphics/Obj.h
  include/network/connection.hpp
  include/network/message.hpp
  include/network/tcp_client.hpp
  include/network/tcp_server.hpp
  src/client/CMakeLists.txt
  src/client/graphics/imported/Tokenizer.cpp
  src/client/main.cpp
  src/network/CMakeLists.txt
  src/network/message.cpp
  src/network/tcp_client.cpp
  src/network/tcp_server.cpp
  src/server/CMakeLists.txt
  src/server/main.cpp
Labels: enhancement

#26 Cleanup CMake configuration
  3rd_party/imgui/CMakeLists.txt
  3rd_party/imgui/LICENSE.txt
  3rd_party/imgui/backends/imgui_impl_glfw.cpp
  3rd_party/imgui/backends/imgui_impl_glfw.h
  3rd_party/imgui/backends/imgui_impl_opengl3.cpp
  3rd_party/imgui/backends/imgui_impl_opengl3.h
  3rd_party/imgui/backends/imgui_impl_opengl3_loader.h
  3rd_party/imgui/imconfig.h
  3rd_party/imgui/imgui.cpp
  3rd_party/imgui/imgui.h
  3rd_party/imgui/imgui_draw.cpp
  3rd_party/imgui/imgui_internal.h
  3rd_party/imgui/imgui_tables.cpp
  3rd_party/imgui/imgui_widgets.cpp
  3rd_party/imgui/imstb_rectpack.h
  3rd_party/imgui/imstb_textedit.h
  3rd_party/imgui/imstb_truetype.h
  3rd_party/imgui/misc/README.txt
  3rd_party/imgui/misc/cpp/README.txt
  3rd_party/imgui/misc/cpp/imgui_stdlib.cpp
  3rd_party/imgui/misc/cpp/imgui_stdlib.h
  CMakeLists.txt
  include/client/graphics/Scene.h
  src/client/CMakeLists.txt
Labels: enhancement

#27 Add config file support
  CMakeLists.txt
  config.json
  include/config/lib.hpp
  include/network/tcp_client.hpp
  src/client/CMakeLists.txt
  src/client/main.cpp
  src/config/CMakeLists.txt
  src/config/lib.cpp
  src/network/tcp_client.cpp
  src/server/CMakeLists.txt
  src/server/main.cpp
Labels: enhancement

#31 Add cpplint for header files
  .github/workflows/build.yml
  CPPLINT.cfg
  include/client/graphics/AnimationClip.h
  include/client/graphics/AnimationPlayer.h
  include/client/graphics/CPPLINT.cfg
  include/client/graphics/Channel.h
  include/client/graphics/Collider.h
  include/client/graphics/Cube.h
  include/client/graphics/GameThing.h
  include/client/graphics/Input.h
  include/client/graphics/InputListener.h
  include/client/graphics/Joint.h
  include/client/graphics/Keyframe.h
  include/client/graphics/Material.h
  include/client/graphics/Mesh.h
  include/client/graphics/Model.h
  include/client/graphics/Node.h
  include/client/graphics/Obj.h
  include/client/graphics/Player.h
  include/client/graphics/PlayerModel.h
  include/client/graphics/Pose.h
  include/client/graphics/Scene.h
  include/client/graphics/Skeleton.h
  include/client/graphics/Skin.h
  include/client/graphics/SkinnedMesh.h
  include/client/graphics/Vertex.h
  include/client/graphics/Window.h
  include/client/graphics/core.h
  include/client/graphics/imported/Tokenizer.h
  include/client/graphics/main.h
  include/client/graphics/shader.h
  include/core/lib.hpp
  include/network/lib.hpp
  include/network/tcp_client.hpp
  src/client/graphics/AnimationClip.cpp
  src/client/graphics/Joint.cpp
  src/client/graphics/Player.cpp
  src/client/graphics/Scene.cpp
  src/client/graphics/Skeleton.cpp
  src/client/graphics/Skin.cpp
  src/client/graphics/SkinnedMesh.cpp
  src/client/graphics/Window.cpp
  src/client/graphics/imported/Tokenizer.cpp
  src/client/main.cpp
  src/network/tcp_client.cpp
  src/network/tcp_server.cpp
  src/server/main.cpp
Labels: enhancement

#36 Add sound library
  assets/sounds/coin.wav
  assets/sounds/hurt.wav
  assets/sounds/hurt2.wav
  assets/sounds/jump.wav
  assets/sounds/jump2.wav
  assets/sounds/sound_test.wav
  assets/sounds/step1.wav
  assets/sounds/step2.wav
  assets/sounds/step3.wav
  assets/sounds/step4.wav
  include/client/graphics/Scene.h
  include/client/graphics/SoundEffect.h
  src/client/CMakeLists.txt
  src/client/graphics/Scene.inl
  src/client/graphics/Window.cpp
Labels: enhancement, graphics

#34 Networking Improvements
  include/network/connection.hpp
  include/network/message.hpp
  include/network/tcp_client.hpp
  include/network/tcp_server.hpp
  src/client/main.cpp
  src/network/CMakeLists.txt
  src/network/lib.cpp
  src/network/message.cpp
  src/network/tcp_client.cpp
  src/network/tcp_server.cpp
  src/server/main.cpp
Labels: enhancement, networking

#39 Add game loop prototype
  CPPLINT.cfg
  include/network/message.hpp
  include/network/tcp_server.hpp
  src/client/main.cpp
  src/network/tcp_server.cpp
Labels: enhancement, networking

#41 Fix core CMake config
  src/core/CMakeLists.txt
Labels: bug, core

#32 Scene interface methods
  include/client/graphics/Camera.h
  include/client/graphics/GameThing.h
  include/client/graphics/Player.h
  include/client/graphics/Scene.h
  include/client/graphics/SceneState.h
  include/client/graphics/UserState.h
  include/client/graphics/Window.h
  include/network/message.hpp
  src/client/graphics/Camera.cpp
  src/client/graphics/Player.cpp
  src/client/graphics/Scene.cpp
  src/client/graphics/Scene.inl
  src/client/graphics/Window.cpp
  src/client/main.cpp
  src/network/tcp_server.cpp
Labels: enhancement, graphics

#44 API improvments, code cleanup
  include/client/graphics/Player.h
  include/network/connection.hpp
  include/network/message.hpp
  include/network/tcp_client.hpp
  include/network/tcp_server.hpp
  src/client/main.cpp
  src/network/message.cpp
  src/network/tcp_client.cpp
  src/network/tcp_server.cpp
Labels: enhancement, networking

#35 Vis skins
  assets/image/IMG_2189.jpg
  assets/image/Skin-unicorn.png
  assets/image/Texture-Bee.JPG
  assets/image/Texture-Cat.JPG
  assets/image/Texture-Duck.JPG
  assets/image/Texture-Racoon.JPG
  assets/image/Texture-Unicorn.JPG
  assets/model/skins/here
  assets/model/skins/skin-avocado.blend
  assets/model/skins/skin-avocado.fbx
  assets/model/skins/skin-bee.blend
  assets/model/skins/skin-bee.fbx
  assets/model/skins/skin-cat.blend
  assets/model/skins/skin-cat.fbx
  assets/model/skins/skin-duck.blend
  assets/model/skins/skin-duck.fbx
  assets/model/skins/skin-racoon.blend
  assets/model/skins/skin-racoon.fbx
  assets/model/skins/skin-unicorn.blend
  assets/model/skins/skin-unicorn.fbx
Labels: visuals

#43 First networked gameplay 🏃
  include/client/graphics/Camera.h
  include/client/graphics/Collider.h
  include/client/graphics/ColliderData.h
  include/client/graphics/ColliderImporter.h
  include/client/graphics/GameThing.h
  include/client/graphics/Player.h
  include/client/graphics/Scene.h
  include/client/graphics/SceneState.h
  include/client/graphics/UserState.h
  include/network/connection.hpp
  include/network/message.hpp
  include/network/tcp_client.hpp
  include/network/tcp_server.hpp
  include/server/game.hpp
  src/client/graphics/Camera.cpp
  src/client/graphics/Player.cpp
  src/client/graphics/Scene.cpp
  src/client/graphics/Scene.inl
  src/client/graphics/Window.cpp
  src/client/main.cpp
  src/core/util/global.cpp
  src/network/message.cpp
  src/network/tcp_client.cpp
  src/network/tcp_server.cpp
  src/server/CMakeLists.txt
  src/server/game.cpp
  src/server/main.cpp
  tests/CMakeLists.txt
Labels: enhancement, core, graphics, networking

#47 Throttle client messages
  include/client/graphics/Camera.h
  include/client/graphics/GameThing.h
  include/client/graphics/Player.h
  include/client/graphics/Scene.h
  include/client/graphics/Window.h
  src/client/graphics/Camera.cpp
  src/client/graphics/Player.cpp
  src/client/graphics/Scene.cpp
  src/client/graphics/Window.cpp
  src/client/main.cpp
Labels: enhancement

#48 Minor game class fixes
  include/server/game.hpp
  src/server/game.cpp
Labels: enhancement, game management

#51 Handle player disconnect, minor client refactor
  include/client/graphics/GameThing.h
  include/client/graphics/Scene.h
  include/client/graphics/Window.h
  include/network/tcp_server.hpp
  include/server/game.hpp
  src/client/graphics/Player.cpp
  src/client/graphics/Scene.cpp
  src/client/graphics/Scene.inl
  src/client/graphics/Window.cpp
  src/client/main.cpp
  src/network/message.cpp
  src/network/tcp_server.cpp
  src/server/game.cpp
  src/server/main.cpp
Labels: enhancement, graphics, networking, game management
